name: NoFlippy-OG
authors: [NotAlexNoyle, Barny1094875]
description: A plugin to prevent trapdoors being flipped in certain regions by certain groups. Made for https://true-og.net/
website: https://github.com/NotAlexNoyle/NoFlippy-OG/
version: 1.2
api-version: 1.18
main: plugin.NoFlippyOG
depend: [WorldGuard]
permissions:
  noflippy.bypass:
    default: false