name: NoFlippy-OG
author: NotAlexNoyle
description: A plugin to prevent trapdoors being flipped in certain regions by certain groups. Made for https://true-og.net/
website: https://github.com/NotAlexNoyle/NoFlippy-OG/
version: 1.0
api-version: 1.18
main: plugin.NoFlippyOG
depend: [WorldGuard]
permissions:
  noflippy.bypass:
    default: false
